name: BeSoEasy
description: I Make Things Work
meta_description: "Best Social Media Bots, Automation Bots, AI Bots"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'https://besoeasy.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://besoeasy.com'
author:         'BeSoEasy'
authorTwitter:  '@besoeasy'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
