#
###################################
# Site wide configuration
####################################
#
title: BeSoEasy
email: besoeasy@protonmail.com
description: All the Software Created By beSoEasy
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: https://besoeasy.com

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  rouge
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: BeSoEasy
  avatar: avatar.jpg
  job: "Web Application Expert"
  bio: "Blockchain, Web Automation, Bots, Hacking Tools, Web Applications."
  email: "besoeasy@protonmail.com"
  disqus-shortname:
  twitter: #username
  facebook: "besoeasy"
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: "besoeasy"
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
